import type * as PrototypeTypes from "./types.ts"

export type {
	CategoryDefinition,
	PrototypeDefinition,
	PrototypeDefinitionBase,
	PrototypeDefinitionPrototype,
	PrototypeDefinitionType,
	PrototypeDefinitionVariant,
	PrototypeDefinitionVariants,
	PrototypeStatus,
	WrapperDefinition,
} from "./types.ts"

// Define wrappers with their display names
export const wrappers: PrototypeTypes.WrapperDefinition[] = [
	{
		id: "Special",
		name: "Special page",
	},
	{
		id: "Chrome",
		name: "Chrome",
	},
	{
		id: "Component",
		name: "Component",
	},
	{
		id: "Fullscreen",
		name: "Fullscreen",
	},
	{
		id: "Mobile",
		name: "Mobile",
	},
]

// Define categories with their descriptions in display order
export const categories: PrototypeTypes.CategoryDefinition[] = [
	{
		id: "dashboard",
		name: "Dashboard",
		description: "Prototypes that imitate the personal dashboard.",
	},
	{
		id: "editor",
		name: "Visual editor",
		description: "Prototypes experimenting with the visual editor.",
	},
	{
		id: "changetypes",
		name: "Change types",
		description: "Feeds enriched with structured change information.",
	},
	{
		id: "flagging",
		name: "Flagging",
		description: "Feeds with flagged items and prediction indicators.",
	},
	{
		id: "recommendations",
		name: "Recommendations",
		description: "Experiments in how to source personalized recommendations.",
	},
	{
		id: "api",
		name: "API",
		description: "Demonstrations of available API.",
	},
	{
		id: "feed",
		name: "Feeds",
		description: "Early experiments for feeds of information.",
	},
	{
		id: "article",
		name: "Article",
		description: "Prototypes that display articles in different ways.",
	},
	{
		id: "page",
		name: "Page",
		description: "Basic demonstrations of working with real page information.",
	},
	{
		id: "search",
		name: "Search",
		description: "Basic demonstrations of search features.",
	},
	{
		id: "wrappers",
		name: "Wrappers",
		description: "Demonstrations of the various wrappers that are available for prototypes.",
	},
	{
		id: "components",
		name: "Components",
		description: "Examples of different Codex components.",
	},
]

export const prototypeMetadata: PrototypeTypes.PrototypeDefinition<"prototype" | "variants">[] = [
	{
		type: "prototype",
		id: "UserRecentPages",
		name: "Recent edits",
		description: "Show the recently edited pages for a single user.",
		category: "dashboard",
		wrapper: "Component",
		title: "Recent edits",
		status: "new",
		featured: true,
	},
	{
		type: "prototype",
		id: "ApiPlayground",
		name: "API Playground",
		description: "Sandbox for every FakeWiki method.",
		category: "api",
		wrapper: "Fullscreen",
		title: "API Playground",
		status: "updated",
		featured: true,
	},
	{
		type: "prototype",
		id: "WikiSignals",
		name: "Wiki signals",
		description:
			"Interactive copy of wiki-signals markdown: run each curl example and see live responses.",
		category: "api",
		wrapper: "Fullscreen",
		title: "Wiki signals",
		status: "new",
		featured: true,
	},
	{
		type: "prototype",
		id: "VeSuggestions",
		name: "Edit suggestions",
		description: "Run all edit suggestion checks for a page in serial.",
		category: "dashboard",
		wrapper: "Component",
		title: "Edit suggestions",
		status: "new",
		featured: true,
	},
	{
		type: "variants",
		id: "RecommendationFeeds",
		name: "Recommendation feeds",
		description: "Feeds that surface personalized or contextual recommendations.",
		category: "recommendations",
		variants: [
			{
				type: "variant",
				id: "RelatedRecommendations",
				title: "Related recommendations",
				name: "Related recommendation feed",
				description: "Feed with recommendations based on related changes.",
				wrapper: "Fullscreen",
				featured: true,
			},
			{
				type: "variant",
				id: "RecommendationWatchlist",
				title: "List-building recommendation watchlist",
				name: "List-building recommendation feed",
				description: "Feed with recommendations based on list-building.",
				wrapper: "Fullscreen",
				featured: true,
			},
		],
	},
	{
		type: "variants",
		id: "RelatedChanges",
		name: "Related changes",
		description: "View and combine recent changes for one or more pages.",
		category: "recommendations",
		variants: [
			{
				type: "variant",
				id: "RelatedChangesMulti",
				title: "Multi-page related changes feed",
				name: "Multi-page related changes",
				description: "Combine related changes from multiple pages.",
				wrapper: "Fullscreen",
				featured: true,
			},
			{
				type: "variant",
				id: "RelatedChanges",
				title: "Related changes feed",
				name: "Related changes",
				description:
					"View recent changes for any page. Enter a page name to see its edit history.",
				wrapper: "Fullscreen",
				featured: true,
			},
		],
	},
	{
		type: "variants",
		id: "ListBuilding",
		name: "List building",
		description:
			"Build a list of articles related to one or more pages using the List Building tool.",
		category: "recommendations",
		variants: [
			{
				type: "variant",
				id: "MultipleListBuilding",
				title: "Multiple list building",
				name: "Multiple list building",
				description:
					"Build a list of articles related to multiple pages using the List Building tool.",
				wrapper: "Fullscreen",
				featured: true,
			},
			{
				type: "variant",
				id: "ListBuilding",
				title: "List building",
				name: "List building",
				description:
					"Build a list of articles related to a page using the List Building tool.",
				wrapper: "Fullscreen",
				featured: true,
			},
		],
	},
	{
		type: "variants",
		id: "LinkExplorers",
		name: "Link explorers",
		description: "Explore page links in different ways.",
		category: "recommendations",
		variants: [
			{
				type: "variant",
				id: "PageLinkSimilarity",
				title: "Page link similarity",
				name: "Page link similarity",
				description: "Explore how similar different pages' links are.",
				wrapper: "Fullscreen",
				featured: true,
			},
			{
				type: "variant",
				id: "PageLinks",
				title: "Page links",
				name: "Page links",
				description:
					"Explore outgoing and incoming links for multiple pages, shown side by side and on a graph.",
				wrapper: "Fullscreen",
				featured: true,
			},
		],
	},
	{
		type: "prototype",
		id: "MaximalistFlagWatchlist",
		name: "Multiple flag watchlist",
		description: "A feed with flags from multiple prediction models.",
		category: "flagging",
		wrapper: "Fullscreen",
		title: "Multiple flag watchlist",
		featured: true,
	},
	{
		type: "prototype",
		id: "FlaggedWatchlist",
		name: "Flag watchlist",
		description: "A feed with flagged items.",
		category: "flagging",
		wrapper: "Fullscreen",
		title: "Flag watchlist",
		featured: true,
	},
	{
		type: "variants",
		id: "StyledWatchlist",
		name: "Styled watchlist",
		description: "Feeds based on the Watchlist, but with more opinionated styling.",
		category: "feed",
		variants: [
			{
				type: "variant",
				id: "MobileFlaggedWatchlist",
				component: "FlaggedWatchlist",
				title: "Mobile flagged watchlist",
				name: "Mobile flagged watchlist",
				description: "A feed with flagged items.",
				wrapper: "Mobile",
			},
			{
				type: "variant",
				id: "ExpandingWatchlist",
				title: "Expanding watchlist",
				name: "Expanding watchlist",
				description: "A feed with expandable items.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "UserWatchlist",
				title: "Re-ordered styled watchlist",
				name: "Re-ordered styled watchlist",
				description:
					"A styled watchlist but with the information re-ordered over multiple lines.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "StyledWatchlistBase",
				title: "Styled watchlist",
				name: "Styled watchlist",
				description: "A watchlist but with more opinionated styling.",
				wrapper: "Special",
			},
		],
	},
	{
		type: "variants",
		id: "StructuredDeltas",
		name: "Structured deltas",
		description: "A watchlist with more helpful deltas.",
		category: "changetypes",
		variants: [
			{
				featured: true,
				type: "variant",
				id: "ChangeTypesWatchlistInline",
				component: "ChangeTypesWatchlistInline",
				title: "Structured deltas",
				name: "Structured deltas",
				description: "A watchlist with more helpful deltas.",
				wrapper: "Fullscreen",
			},
			{
				featured: true,
				type: "variant",
				id: "DeltaSnippets",
				component: "DeltaSnippets",
				title: "Delta snippets",
				name: "Delta snippets",
				description: "Structured deltas with snippet previews when expanded.",
				wrapper: "Fullscreen",
			},
		],
	},
	{
		type: "prototype",
		id: "ChangeTypesWatchlistDetails",
		title: "Change types",
		name: "Change types",
		description: "A watchlist that shows information about changes when opened.",
		category: "changetypes",
		wrapper: "Fullscreen",
		featured: true,
	},
	{
		type: "variants",
		id: "Watchlist",
		name: "Watchlist",
		description: "Feed variants that present results like the Watchlist.",
		category: "feed",
		variants: [
			{
				type: "variant",
				id: "SmoothWatchlistInlineDiff",
				title: "Inline watchlist",
				name: "Inline watchlist",
				description:
					"A watchlist where you can open a diff inline by using the diff button.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "SmoothWatchlistIndented",
				title: "Indented watchlist",
				name: "Indented watchlist",
				description:
					"A watchlist where the edit summary and CTAs are indented on their own lines. ",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "SmoothWatchlist",
				title: "Re-ordered watchlist",
				name: "Re-ordered watchlist",
				description:
					"Presents results like the Watchlist, but with the information in each result re-ordered to group similar information together.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "WatchlistFeed",
				title: "Combined watchlist",
				name: "Combined watchlist",
				description: "Presents results exactly like the Watchlist.",
				wrapper: "Special",
			},
		],
	},
	{
		type: "variants",
		id: "DiffFeed",
		name: "Diff feed",
		description: "A feed that shows inline diffs of changes.",
		category: "feed",
		variants: [
			{
				type: "variant",
				id: "DiffFeedStyled",
				title: "Diff feed",
				name: "Diff feed",
				description: "A feed that shows inline diffs.",
				wrapper: "Special",
			},
			// {
			// 	type: "variant",
			// 	id: "DiffFeedPlain",
			// 	title: "Diff feed",
			// 	name: "Diff feed",
			// 	description: "A feed that shows inline diffs.",
			// 	wrapper: "Special",
			// },
			// {
			// 	type: "variant",
			// 	id: "DiffFeed",
			// 	title: "Diff user feed",
			// 	name: "Diff user feed",
			// 	description: "A feed that shows inline diffs with user avatars.",
			// 	wrapper: "Special",
			// },
			// {
			// 	type: "variant",
			// 	id: "DiffFeedThumbnail",
			// 	title: "Diff page feed",
			// 	name: "Diff page feed",
			// 	description: "A feed that shows inline diffs with page thumbnails.",
			// 	wrapper: "Special",
			// },
		],
	},

	{
		type: "variants",
		id: "CombinedFeed",
		name: "Combined feed",
		description: "A feed that combines multiple sources into one.",
		category: "feed",
		variants: [
			{
				type: "variant",
				id: "CombinedFeedMinimal",
				title: "Combined feed",
				name: "Combined feed",
				description: "A stripped-back combined feed with no avatar or thumbnail.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "CustomPageFeed",
				title: "Combined user feed",
				name: "Combined user feed",
				description: "A combined feed that presents results exactly like the Custom page.",
				wrapper: "Special",
			},
			{
				type: "variant",
				id: "CustomThumbnailFeed",
				title: "Combined page feed",
				name: "Combined page feed",
				description: "Use the page as the primary source.",
				wrapper: "Special",
			},
		],
	},
	{
		type: "prototype",
		id: "MultiPageFeed",
		name: "Multi-page feed",
		description: "A feed that combines updates from multiple pages.",
		category: "feed",
		wrapper: "Component",
		title: "Multi-page feed",
	},
	{
		type: "variants",
		id: "PageFeed",
		name: "Page feed",
		description: "A feed component that shows recent changes to a page.",
		category: "feed",
		variants: [
			{
				id: "PageFeedLined",
				name: "Lined variant",
				description: "Use lines to separate changes.",
				wrapper: "Component",
				title: "Lined feed",
				type: "variant",
			},
			{
				id: "PageFeed",
				name: "Card variant",
				description: "Use cards to display changes.",
				wrapper: "Component",
				title: "Card feed",
				type: "variant",
			},
		],
	},
	{
		type: "prototype",
		id: "PageChanges",
		name: "Page changes",
		description: "How to get a page's recent changes from the API.",
		category: "feed",
		wrapper: "Component",
		title: "Page changes",
	},
	{
		type: "prototype",
		id: "SearchTitles",
		name: "Search titles",
		description: "How to search page titles using the API.",
		category: "search",
		wrapper: "Component",
		title: "Search titles",
	},
	{
		type: "prototype",
		id: "SearchPages",
		name: "Search pages",
		description: "How to search page content using the API.",
		category: "search",
		wrapper: "Component",
		title: "Search pages",
	},
	{
		type: "prototype",
		id: "MoreLikeSearch",
		name: "More like search",
		description: "Get 'more like' recommendations from a set of seed pages.",
		category: "search",
		wrapper: "Component",
		title: "More like search",
		featured: true,
		status: "new",
	},
	{
		type: "prototype",
		id: "SearchUsers",
		name: "Search users",
		description: "How to search user accounts using the API.",
		category: "search",
		wrapper: "Component",
		title: "Search users",
	},
	{
		type: "prototype",
		id: "FeaturedPage",
		name: "Featured page",
		description: "How to get a featured page from the API.",
		category: "api",
		wrapper: "Component",
		title: "Featured page",
	},
	{
		type: "prototype",
		id: "OnThisDay",
		name: "On this day",
		description: "How to get pages that relate to a specific date.",
		category: "api",
		wrapper: "Component",
		title: "On this day",
	},
	{
		type: "prototype",
		id: "WikitextTransform",
		name: "Wikitext transform",
		description: "How to transform wikitext to HTML using the API.",
		category: "api",
		wrapper: "Component",
		title: "Wikitext transform",
	},
	{
		type: "prototype",
		id: "VisualEditorSandbox",
		name: "Visual editor",
		description: "Embedded visual editor.",
		category: "editor",
		wrapper: "Fullscreen",
		title: "Visual editor",
		featured: true,
	},
	{
		type: "prototype",
		id: "VisualDiff",
		name: "Visual diff",
		description: "Compare two snippets with the visual editor's diff view.",
		category: "editor",
		wrapper: "Fullscreen",
		title: "Visual diff",
		featured: true,
	},
	{
		type: "prototype",
		id: "ExpandingWatchlistVisualDiff",
		name: "Visual diff feed",
		description: "A feed of changes that shows visual inline diffs instead of wikitext diffs.",
		category: "editor",
		wrapper: "Fullscreen",
		title: "Visual diff feed",
		featured: true,
	},

	{
		type: "variants",
		id: "RecentChangeSources",
		name: "Recent change sources",
		description: "Debugging playground for comparing and scoring edit-feed sources.",
		category: "dashboard",
		featured: true,
		status: "new",
		variants: [
			{
				type: "variant",
				id: "PageAndRecentChangeSources",
				name: "Page and recent change sources",
				description:
					"A two phase system that first gathers page recommendations and then gathers changes from those pages.",
				wrapper: "Fullscreen",
				title: "Page and recent change sources",
				featured: true,
				status: "new",
			},
			{
				type: "variant",
				id: "RecentChangeSources",
				name: "Recent change sources",
				description: "A one phase system that gathers change recommendations directly.",
				wrapper: "Fullscreen",
				title: "Recent change sources",
				featured: true,
				status: "new",
			},
		],
	},
	{
		type: "prototype",
		id: "PersonalDashboardPlus",
		name: "Personal dashboard plus",
		description: "What the personal dashboard could be.",
		category: "dashboard",
		wrapper: "Special",
		title: "Personal dashboard plus",
		status: "updated",
		featured: true,
	},
	{
		type: "prototype",
		id: "PersonalDashboardClone",
		name: "Personal dashboard playground",
		description: "A clone of the personal dashboard.",
		category: "dashboard",
		wrapper: "Special",
		title: "Personal dashboard",
		status: "updated",
		featured: true,
	},
	{
		type: "prototype",
		id: "ReviewChanges",
		name: "Review changes",
		description: "The review changes feed, standalone.",
		category: "dashboard",
		wrapper: "Chrome",
		title: "Review changes",
		hidden: true,
	},
	{
		type: "prototype",
		id: "ReviewChangesPlus",
		name: "Review changes plus",
		description: "What the review changes feed could be like.",
		category: "dashboard",
		wrapper: "Chrome",
		title: "Review changes plus",
		hidden: true,
	},
	{
		type: "prototype",
		id: "PageMetadata",
		name: "Page metadata",
		description: "How to get a page's metadata from the API.",
		category: "page",
		wrapper: "Fullscreen",
		title: "Page metadata",
	},
	{
		type: "variants",
		id: "PageHtml",
		name: "Page HTML",
		description: "How to retrieve and render the HTML of a page.",
		category: "page",
		variants: [
			{
				id: "PageHtml",
				name: "Desktop page HTML",
				description: "Get a desktop page.",
				wrapper: "Component",
				type: "variant",
				title: "Desktop HTML",
			},
			{
				id: "PageMobileHtml",
				name: "Mobile page HTML",
				description: "Get a mobile page.",
				wrapper: "Component",
				type: "variant",
				title: "Mobile HTML",
			},
		],
	},
	{
		type: "prototype",
		id: "PageSource",
		name: "Page source",
		description: "How to get a page's source.",
		category: "page",
		wrapper: "Fullscreen",
		title: "Page source",
	},
	{
		type: "prototype",
		id: "PageMedia",
		name: "Page media",
		description: "How to get a page's media items.",
		category: "page",
		wrapper: "Component",
		title: "Page media",
	},
	{
		type: "prototype",
		id: "RandomPage",
		name: "Random page",
		description: "How to get a random page from the API.",
		category: "api",
		wrapper: "Component",
		title: "Random page",
	},
	{
		type: "prototype",
		id: "HistoryCacheInspector",
		name: "History cache",
		description: "Debug the history cache for combined feeds.",
		category: "api",
		wrapper: "Fullscreen",
		title: "History cache inspector",
	},
	{
		type: "prototype",
		id: "Page",
		name: "Page summary",
		description: "How to get a page's summary.",
		category: "page",
		wrapper: "Component",
		title: "Page summary",
	},
	{
		type: "prototype",
		id: "WikiArticle",
		name: "Tabbed article",
		description: "Display an article in a tabbed layout.",
		category: "article",
		wrapper: "Mobile",
		title: "Tabbed article",
		status: "wip",
		featured: true,
	},
	{
		type: "prototype",
		id: "Chip",
		name: "Filter",
		description: "An example of a chip filter component.",
		category: "components",
		wrapper: "Component",
		title: "Filter",
	},
	{
		type: "prototype",
		id: "Card",
		name: "Card",
		description: "How to use a card component.",
		category: "components",
		wrapper: "Component",
		title: "Card",
	},
	{
		type: "prototype",
		id: "Counter",
		name: "Button",
		description: "How to use a button component.",
		category: "components",
		wrapper: "Component",
		title: "Button",
	},
	{
		type: "prototype",
		id: "HelloWorld",
		name: "Hello world",
		description: "How to use codex components.",
		category: "components",
		wrapper: "Component",
		title: "Hello world",
	},

	{
		type: "prototype",
		id: "WrapperDemo-Special",
		component: "WrapperDemo",
		title: "Special page wrapper",
		name: "Special page wrapper",
		description: "View this prototype in the Special page layout.",
		wrapper: "Special",
		category: "wrappers",
	},
	{
		type: "prototype",
		id: "WrapperDemo-Component",
		component: "WrapperDemo",
		title: "Component wrapper",
		name: "Component wrapper",
		description: "View this prototype in the Component (tablet) layout.",
		wrapper: "Component",
		category: "wrappers",
	},
	{
		type: "prototype",
		id: "WrapperDemo-Fullscreen",
		component: "WrapperPaddingDemo",
		title: "Fullscreen wrapper",
		name: "Fullscreen wrapper",
		description: "View this prototype in the Fullscreen layout.",
		wrapper: "Fullscreen",
		category: "wrappers",
	},
	{
		type: "prototype",
		id: "WrapperDemo-Mobile",
		component: "WrapperPaddingDemo",
		title: "Mobile wrapper",
		name: "Mobile wrapper",
		description: "View this prototype in the Mobile layout (phone frame on large screens).",
		wrapper: "Mobile",
		category: "wrappers",
	},
]
