/**
 * Build-time script: parses FakeWiki.ts and hooks TSDoc to emit playground-schema.generated.ts,
 * packages/fakewiki/AGENTS.md, repo-root public/llms.txt, public/llms.html, and
 * src/prototypes/FakeWikiReference/generated/llms-body.ts and generated/llms.vue (reference panel body).
 * The `npm run generate` script in this package runs WikiSignals (`build-real-data-reference.mjs`) first, then this file.
 * To regenerate only the schema/AGENTS/llms steps (skip WikiSignals), run: npx tsx scripts/generate-schema.ts
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"
import * as ts from "typescript"

import {
	extractFakeWikiMethods,
	loadAllHookSchemas,
	type HookSchema,
	type MethodSchema,
} from "./lib/doc-parse"
import { renderAgentsMarkdownToHtml } from "./lib/render-reference-html"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pkgRoot = path.dirname(__dirname)
const repoRoot = path.dirname(path.dirname(pkgRoot))
const FAKEWIKI_PATH = path.join(pkgRoot, "FakeWiki.ts")
const HOOKS_DIR = path.join(pkgRoot, "hooks")
const OUT_PLAYGROUND = path.join(pkgRoot, "playground-schema.generated.ts")
const OUT_AGENTS = path.join(pkgRoot, "AGENTS.md")
const OUT_LLMS = path.join(repoRoot, "public", "llms.txt")
const OUT_LLMS_HTML = path.join(repoRoot, "public", "llms.html")
const OUT_REFERENCE_BODY_TS = path.join(
	repoRoot,
	"src",
	"prototypes",
	"FakeWikiReference",
	"generated",
	"llms-body.ts"
)
const OUT_REFERENCE_LLM_S_VUE = path.join(
	repoRoot,
	"src",
	"prototypes",
	"FakeWikiReference",
	"generated",
	"llms.vue"
)

function jsonStringLiteral(s: string): string {
	return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`
}

function emitLlmSBodyTsModule(referenceHtml: string): string {
	return `/** AUTO-GENERATED by packages/fakewiki/scripts/generate-schema.ts — do not edit. */
export const llmsReferenceBodyHtml: string = ${JSON.stringify(referenceHtml)}
`
}

function emitLlmSVueFile(): string {
	return `<!-- AUTO-GENERATED by packages/fakewiki/scripts/generate-schema.ts — do not edit. -->
<template>
	<div class="rds-md fwr-generated-body" v-memo="[html]" v-html="html" />
</template>

<script setup lang="ts">
import { llmsReferenceBodyHtml as html } from "./llms-body"
</script>
`
}

function emitTs(methods: MethodSchema[]): string {
	const lines: string[] = [
		"// AUTO-GENERATED by scripts/generate-schema.ts - do not edit manually",
		"",
		"export type PlaygroundParamSchema = { key: string; description?: string }",
		"",
		"export type PlaygroundMethodSchema = { name: string; description?: string; category?: string; params: PlaygroundParamSchema[]; examples?: string[] }",
		"",
		"export const playgroundSchema: PlaygroundMethodSchema[] = [",
	]
	for (const m of methods) {
		const desc = m.description ? jsonStringLiteral(m.description) : "undefined"
		const paramsJson = m.params
			.map(
				p =>
					`      { key: "${p.key}"${p.description ? `, description: ${jsonStringLiteral(p.description)}` : ""} }`
			)
			.join(",\n")
		const category = m.category ? jsonStringLiteral(m.category) : "undefined"
		const exBlock =
			m.examples && m.examples.length > 0
				? `, examples: [${m.examples.map(e => jsonStringLiteral(e)).join(", ")}]`
				: ""
		lines.push(`  { name: "${m.name}", description: ${desc}, category: ${category}, params: [`)
		lines.push(paramsJson)
		lines.push(`  ]${exBlock} },`)
	}
	lines.push("]")
	return lines.join("\n")
}

function mdEscapeInline(s: string): string {
	return (
		s
			.replace(/\|/g, "\\|")
			// Avoid UTF-8 dash mojibake (e.g. â€") when llms.txt is read as Latin-1
			.replace(/[\u2010\u2011\u2012\u2013\u2014\u2015]/g, "-")
	)
}

function pushExamplesMarkdown(lines: string[], examples: string[] | undefined) {
	if (!examples?.length) return
	lines.push(examples.length === 1 ? "**Example**" : "**Examples**")
	lines.push("")
	for (const ex of examples) {
		const t = ex.trim()
		if (t.startsWith("```")) {
			lines.push(t)
		} else {
			lines.push("```ts")
			lines.push(t)
			lines.push("```")
		}
		lines.push("")
	}
}

function emitAgentsMarkdown(methods: MethodSchema[], hooks: HookSchema[]): string {
	const lines: string[] = []
	lines.push("# fakewiki API reference")
	lines.push("")
	lines.push("<!-- AUTO-GENERATED by scripts/generate-schema.ts - do not edit manually -->")
	lines.push("")
	lines.push(
		"This file lists `FakeWiki` instance methods and Vue composables exported from the `fakewiki` package. Regenerate with `npm run generate` from the repository root or from `packages/fakewiki`."
	)
	lines.push("")
	lines.push(
		"- FakeWiki playground: https://todepond.github.io/FakeMediaWiki/Fullscreen/ApiPlayground"
	)
	lines.push("- Repository: https://github.com/todepond/FakeMediaWiki")
	lines.push("- Package: https://www.npmjs.com/package/fakewiki")
	lines.push("")

	lines.push("## FakeWiki instance methods")
	lines.push("")

	const byCategory = new Map<string, MethodSchema[]>()
	const uncategorized: MethodSchema[] = []
	for (const m of methods) {
		if (m.category) {
			if (!byCategory.has(m.category)) byCategory.set(m.category, [])
			byCategory.get(m.category)!.push(m)
		} else {
			uncategorized.push(m)
		}
	}
	for (const arr of byCategory.values()) {
		arr.sort((a, b) => a.name.localeCompare(b.name))
	}
	uncategorized.sort((a, b) => a.name.localeCompare(b.name))

	const emitMethod = (m: MethodSchema) => {
		lines.push(`#### \`${m.name}\``)
		lines.push("")
		if (m.description) {
			lines.push(mdEscapeInline(m.description))
			lines.push("")
		}
		if (m.params.length > 0) {
			lines.push("**Parameters**")
			lines.push("")
			for (const p of m.params) {
				const desc = p.description ? ` - ${mdEscapeInline(p.description)}` : ""
				lines.push(`- \`${p.key}\`${desc}`)
			}
			lines.push("")
		}
		pushExamplesMarkdown(lines, m.examples)
	}

	const sortedCats = [...byCategory.keys()].sort((a, b) => a.localeCompare(b))
	for (const cat of sortedCats) {
		lines.push(`### Category: ${cat}`)
		lines.push("")
		for (const m of byCategory.get(cat)!) {
			emitMethod(m)
		}
	}
	if (uncategorized.length > 0) {
		lines.push("### General (no `@category` in JSDoc)")
		lines.push("")
		for (const m of uncategorized) {
			emitMethod(m)
		}
	}

	lines.push("## Vue composables (`fakewiki` / `fakewiki/hooks`)")
	lines.push("")

	for (const h of hooks) {
		lines.push(`### \`${h.name}\``)
		lines.push("")
		lines.push(`*Source:* \`hooks/${h.fileBase}\``)
		lines.push("")
		if (h.description) {
			lines.push(mdEscapeInline(h.description))
			lines.push("")
		}
		if (h.params.length > 0) {
			lines.push("**Parameters (from JSDoc `@param` where present)**")
			lines.push("")
			for (const p of h.params) {
				const desc = p.description ? ` - ${mdEscapeInline(p.description)}` : ""
				lines.push(`- \`${p.key}\`${desc}`)
			}
			lines.push("")
		}
		if (h.paramsSource) {
			lines.push("```ts")
			lines.push(`${h.name}(${h.paramsSource})`)
			lines.push("```")
			lines.push("")
		}
		pushExamplesMarkdown(lines, h.examples)
		lines.push(`*Import:* \`import { ${h.name} } from "fakewiki"\``)
		lines.push("")
	}

	return lines.join("\n")
}

const content = fs.readFileSync(FAKEWIKI_PATH, "utf-8")
const sourceFile = ts.createSourceFile(FAKEWIKI_PATH, content, ts.ScriptTarget.Latest, true)
const methods = extractFakeWikiMethods(sourceFile)
const hooks = loadAllHookSchemas(HOOKS_DIR)

const playgroundOut = emitTs(methods)
fs.writeFileSync(OUT_PLAYGROUND, playgroundOut, "utf-8")
console.log(`Wrote ${methods.length} methods to ${OUT_PLAYGROUND}`)

const markdown = emitAgentsMarkdown(methods, hooks)
fs.writeFileSync(OUT_AGENTS, markdown, "utf-8")
console.log(`Wrote AGENTS.md (${methods.length} methods, ${hooks.length} hooks) to ${OUT_AGENTS}`)

fs.mkdirSync(path.dirname(OUT_LLMS), { recursive: true })
fs.writeFileSync(OUT_LLMS, markdown, "utf-8")
console.log(`Wrote llms.txt to ${OUT_LLMS}`)

const referenceHtml = renderAgentsMarkdownToHtml(markdown)
fs.writeFileSync(OUT_LLMS_HTML, referenceHtml, "utf-8")
console.log(`Wrote pre-rendered reference HTML to ${OUT_LLMS_HTML}`)

fs.mkdirSync(path.dirname(OUT_REFERENCE_BODY_TS), { recursive: true })
fs.writeFileSync(OUT_REFERENCE_BODY_TS, emitLlmSBodyTsModule(referenceHtml), "utf-8")
console.log(`Wrote FakeWikiReference llms-body module to ${OUT_REFERENCE_BODY_TS}`)

fs.writeFileSync(OUT_REFERENCE_LLM_S_VUE, emitLlmSVueFile(), "utf-8")
console.log(`Wrote FakeWikiReference llms.vue to ${OUT_REFERENCE_LLM_S_VUE}`)
