/**
 * Build-time script: parses FakeWiki.ts and its TSDoc to emit playground-schema.generated.ts.
 * Run from repo root: npx tsx packages/fakewiki/scripts/generate-playground-schema.ts
 * Or from packages/fakewiki: npm run generate:playground
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"
import * as ts from "typescript"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pkgRoot = path.dirname(__dirname)
const FAKEWIKI_PATH = path.join(pkgRoot, "FakeWiki.ts")
const OUT_PATH = path.join(pkgRoot, "playground-schema.generated.ts")

function getFullText(node: ts.Node, sourceFile: ts.SourceFile): string {
	return sourceFile.getFullText().slice(node.getStart(sourceFile), node.getEnd())
}

function getJSDocComment(node: ts.Node, sourceFile: ts.SourceFile): string | undefined {
	// Leading trivia (whitespace + comment) is between getFullStart() and getStart()
	const fullStart = node.getFullStart()
	const start = node.getStart(sourceFile)
	const leading = sourceFile.getFullText().slice(fullStart, start)
	const match = leading.match(/\/\*\*[\s\S]*?\*\//)
	return match ? match[0] : undefined
}

function parseParamTags(jsdoc: string): Map<string, string> {
	const params = new Map<string, string>()
	const paramRe = /\@param\s+(\w+)\s+[-–—]\s*([^\n*]+)/g
	let m
	while ((m = paramRe.exec(jsdoc)) !== null) {
		params.set(m[1], m[2].trim())
	}
	return params
}

function getSummary(jsdoc: string): string | undefined {
	const lines = jsdoc.replace(/^\s*\/\*\*?\s*/, "").replace(/\s*\*\/\s*$/, "").split(/\n/)
	const summary: string[] = []
	for (const line of lines) {
		const trimmed = line.replace(/^\s*\*\s?/, "").trim()
		if (trimmed.startsWith("@") || trimmed === "") break
		summary.push(trimmed)
	}
	return summary.length ? summary.join("\n").trim() : undefined
}

function getCategory(jsdoc: string): string | undefined {
	const match = jsdoc.match(/\@category\s+([^\n*]+)/)
	return match?.[1]?.trim()
}

type ParamSchema = { key: string; description?: string }
type MethodSchema = { name: string; description?: string; category?: string; params: ParamSchema[] }

function extractMethods(sourceFile: ts.SourceFile): MethodSchema[] {
	const methods: MethodSchema[] = []

	function visit(node: ts.Node): void {
		if (ts.isClassDeclaration(node)) {
			const name = node.name?.getText(sourceFile)
			if (name === "FakeWiki") {
				for (const member of node.members) {
					if (ts.isMethodDeclaration(member)) {
						const modifiers = ts.canHaveModifiers(member) ? ts.getModifiers(member) : undefined
						const isPrivate = modifiers?.some((m) => m.kind === ts.SyntaxKind.PrivateKeyword)
						const isProtected = modifiers?.some((m) => m.kind === ts.SyntaxKind.ProtectedKeyword)
						const methodName = (member.name as ts.Identifier).getText(sourceFile)
						if (isPrivate || isProtected || methodName === "request" || methodName.startsWith("_"))
							continue

						const jsdoc = getJSDocComment(member, sourceFile)
						const paramDocs = jsdoc ? parseParamTags(jsdoc) : new Map<string, string>()
						const description = jsdoc ? getSummary(jsdoc) : undefined
						const category = jsdoc ? getCategory(jsdoc) : undefined

						const params: ParamSchema[] = []
						for (const param of member.parameters) {
							const paramName = (param.name as ts.Identifier).getText(sourceFile)
							params.push({
								key: paramName,
								description: paramDocs.get(paramName),
							})
						}
						methods.push({ name: methodName, description, category, params })
					}
				}
			}
		}
		ts.forEachChild(node, visit)
	}
	visit(sourceFile)
	return methods
}

function emitTs(methods: MethodSchema[]): string {
	const lines: string[] = [
		"// AUTO-GENERATED by scripts/generate-playground-schema.ts – do not edit manually",
		"",
		"export type PlaygroundParamSchema = { key: string; description?: string }",
		"",
		"export type PlaygroundMethodSchema = { name: string; description?: string; category?: string; params: PlaygroundParamSchema[] }",
		"",
		"export const playgroundSchema: PlaygroundMethodSchema[] = [",
	]
	for (const m of methods) {
		const desc = m.description
			? `"${m.description.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`
			: "undefined"
		const paramsJson = m.params
			.map(
				(p) =>
					`      { key: "${p.key}"${p.description ? `, description: "${p.description.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"` : ""} }`
			)
			.join(",\n")
		const category = m.category
			? `"${m.category.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`
			: "undefined"
		lines.push(`  { name: "${m.name}", description: ${desc}, category: ${category}, params: [`)
		lines.push(paramsJson)
		lines.push("  ] },")
	}
	lines.push("]")
	return lines.join("\n")
}

const content = fs.readFileSync(FAKEWIKI_PATH, "utf-8")
const sourceFile = ts.createSourceFile(
	FAKEWIKI_PATH,
	content,
	ts.ScriptTarget.Latest,
	true
)
const methods = extractMethods(sourceFile)
const out = emitTs(methods)
fs.writeFileSync(OUT_PATH, out, "utf-8")
console.log(`Wrote ${methods.length} methods to ${OUT_PATH}`)
