// AUTO-GENERATED by scripts/generate-playground-schema.ts – do not edit manually

export type PlaygroundParamSchema = { key: string; description?: string }

export type PlaygroundMethodSchema = { name: string; description?: string; params: PlaygroundParamSchema[] }

export const playgroundSchema: PlaygroundMethodSchema[] = [
  { name: "getPageSummary", description: "Get a page summary (extract, thumbnail, etc.)", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPageHtml", description: "Get page content as HTML", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPageSource", description: "Get page content as wikitext source", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPage", description: "Get full page metadata and latest revision", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "searchTitles", description: "Search for pages by title (autocomplete-style)", params: [
      { key: "query", description: "Search query" },
      { key: "limit", description: "Maximum results (default: DEFAULT_SEARCH_LIMIT)" }
  ] },
  { name: "searchPages", description: "Full-text search across page titles and content", params: [
      { key: "query", description: "Search query" },
      { key: "limit", description: "Maximum results (default: DEFAULT_SEARCH_LIMIT)" }
  ] },
  { name: "searchUsers", description: "Search for users by username (without avatars).", params: [
      { key: "query", description: "Search query (username or part of username)" },
      { key: "limit", description: "Maximum results (default: DEFAULT_SEARCH_LIMIT)" }
  ] },
  { name: "searchUsersWithAvatars", description: "Search for users by username and fetch their avatars.", params: [
      { key: "query", description: "Search query (username or part of username)" },
      { key: "limit", description: "Maximum results (default: DEFAULT_SEARCH_LIMIT)" }
  ] },
  { name: "getPageHistory", description: "Get page revision history\nUses caching to avoid fetching the same data twice.\nUses older_than/newer_than cursors for pagination and filtering.", params: [
      { key: "pageName", description: "Page title" },
      { key: "options", description: "Options" }
  ] },
  { name: "getUserHistory", description: "Get user contribution history (revisions made by a user)\nUses caching to avoid fetching the same data twice.\nUses older_than/newer_than cursors for pagination and filtering.", params: [
      { key: "userName", description: "Username" },
      { key: "options", description: "Options" }
  ] },
  { name: "getUsersHistory", description: "Get contributions for multiple users by calling getUserHistory for each.\nUses caching to avoid fetching the same data twice.\nFetches user histories in parallel.", params: [
      { key: "userNames", description: "Array of usernames" },
      { key: "options", description: "Options" }
  ] },
  { name: "getCombinedFeed", description: "Get a combined feed of revisions from multiple users and/or pages.\nReturns revisions that match ANY of the provided users OR pages, deduplicated and sorted by timestamp.\nCaching is handled internally by getUserHistory and getPageHistory.", params: [
      { key: "options", description: "Configuration object" }
  ] },
  { name: "getParentRevisionId", description: "Get the parent (previous) revision ID for a revision on a page.\nUses the page history endpoint with older_than so we don't rely on the\ncurrent list having the previous revision.", params: [
      { key: "pageName", description: "Page title" },
      { key: "revId", description: "Revision ID (we want the revision immediately older than this)" }
  ] },
  { name: "compareRevisions", description: "Compare two revisions", params: [
      { key: "fromRevId", description: "Source revision ID (older)" },
      { key: "toRevId", description: "Target revision ID (newer)" }
  ] },
  { name: "getRevisionSource", description: "Get wikitext source for a revision by ID.", params: [
      { key: "revId", description: "Revision ID" }
  ] },
  { name: "getRevisionDiff", description: "Get diff for a revision by comparing it with its parent (previous) revision.\nWhen there is no parent (e.g. first revision), returns a synthetic diff where\nevery line is shown as added.", params: [
      { key: "pageName", description: "Page title" },
      { key: "revId", description: "Revision ID to diff" }
  ] },
  { name: "getRandomPage", description: "Get a random page", params: [
      { key: "format", description: "Format: 'summary', 'html', or 'title' (default: 'summary')" }
  ] },
  { name: "getFeaturedPage", description: "Get featured page for a specific date", params: [
      { key: "date", description: "Date object or YYYY/MM/DD string" }
  ] },
  { name: "getOnThisDay", description: "Get \"On This Day\" content for a given type", params: [
      { key: "type", description: "Type: 'events', 'births', 'deaths', 'holidays', 'selected'" },
      { key: "date", description: "Date object or MM/DD string" }
  ] },
  { name: "getAnnouncements", description: "Get current announcements", params: [

  ] },
  { name: "getPageMedia", description: "Get page media (images, audio, etc.)", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPagesLinks", description: "Get outgoing wikilinks for multiple pages (intra-language links)\nAutomatically handles pagination to fetch all links.", params: [
      { key: "pageNames", description: "Array of page titles" },
      { key: "options", description: "Options" }
  ] },
  { name: "getPagesLinksAndBacklinks", description: "Get outgoing links and backlinks for the given pages in one call.\nConvenience that runs getPagesLinks and getPagesBacklinks in parallel.", params: [
      { key: "pageNames", description: "Array of page titles" },
      { key: "options", description: "Options (namespace for both; backlinkLimit for backlinks only)" }
  ] },
  { name: "getPagesBacklinks", description: "Get pages that link to the given page(s) (backlinks / \"What links here\")\nUses MediaWiki Action API prop=linkshere.", params: [
      { key: "pageNames", description: "Array of page titles to find backlinks for" },
      { key: "options", description: "Options" }
  ] },
  { name: "getRelatedChanges", description: "Get related changes using the Action API feedrecentchanges (1–2 requests total).\nReturns recent edits on pages linked from the target (outgoing) and/or pages that link to the target (incoming).", params: [
      { key: "targetPageName", description: "Page title to get related changes for" },
      { key: "options", description: "showOutgoing: changes on pages the target links to (default true); showIncoming: changes on pages that link to the target (default true); limit: max items per direction 1–50 (default 50); days: 1–30 (default 7); from: optional lower-bound timestamp; to: optional upper-bound timestamp (useful for older-page pagination)" }
  ] },
  { name: "getPageThumbnail", description: "Get thumbnail image for a page.\nUses the lead image (page summary) when available; otherwise falls back to the\nfirst image on the page (e.g. infobox image).", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPageThumbnails", description: "Get thumbnail URLs for multiple pages (lead image from each page).\nUses the Action API pageimages in batches of 50.", params: [
      { key: "pageNames", description: "Page titles" },
      { key: "baseUrl", description: "Wiki base URL (e.g. https://en.wikipedia.org/). Defaults to this.base" }
  ] },
  { name: "getListBuilding", description: "Get a list of articles related to a seed page from the list-building API.\nCombines results from readers, content (links), and morelike models (serpentine order).", params: [
      { key: "lang", description: "Language code (e.g. \"en\")" },
      { key: "options", description: "Optional page title (seed), QID, and per-source result count (default 10)" }
  ] },
  { name: "getPageHero", description: "Get page hero image: thumbnail if present, otherwise the first media image.", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "transformWikitextToHtml", description: "Transform wikitext to HTML", params: [
      { key: "wikitext", description: "Wikitext content" },
      { key: "pageTitle", description: "Page title for context (optional)" }
  ] },
  { name: "getPageCategories", description: "Get page categories", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getPageMobileHtml", description: "Get page mobile-optimized HTML", params: [
      { key: "pageName", description: "Page title" }
  ] },
  { name: "getUserAvatar", description: "Infer a user avatar image from their user page", params: [
      { key: "userName", description: "Username" }
  ] },
  { name: "getUserInfo", description: "Get user information including edit count, registration date, and account type\nResults are cached in memory to avoid repeated API calls for the same user.", params: [
      { key: "userName", description: "Username or IP address" }
  ] },
  { name: "getUserCategory", description: "Get a user's category (cache-aware main entry point).\nReads from category cache when available; otherwise fetches user info and caches the result.", params: [
      { key: "userName", description: "Username to classify" }
  ] },
  { name: "getEditSummaryHtml", description: "Get the HTML representation of an edit summary", params: [
      { key: "summary", description: "Edit summary to get the HTML representation of" },
      { key: "pageName", description: "Page name" }
  ] },
  { name: "getDamagingPrediction", description: "Get damaging prediction for a single revision from Lift Wing API", params: [
      { key: "revisionId", description: "Revision ID" },
      { key: "wiki", description: "Wiki code (e.g., \"enwiki\"). If not provided, extracted from base URL" }
  ] },
  { name: "getGoodfaithPrediction", description: "Get goodfaith prediction for a single revision from Lift Wing API", params: [
      { key: "revisionId", description: "Revision ID" },
      { key: "wiki", description: "Wiki code (e.g., \"enwiki\"). If not provided, extracted from base URL" }
  ] },
  { name: "getDamagingPredictions", description: "Get damaging predictions for multiple revisions in parallel", params: [
      { key: "revisionIds", description: "Array of revision IDs" },
      { key: "wiki", description: "Wiki code (e.g., \"enwiki\"). If not provided, extracted from base URL" }
  ] },
  { name: "getGoodFaithPredictions", description: "Get goodfaith predictions for multiple revisions in parallel", params: [
      { key: "revisionIds", description: "Array of revision IDs" },
      { key: "wiki", description: "Wiki code (e.g., \"enwiki\"). If not provided, extracted from base URL" }
  ] },
  { name: "getRevisionPredictions", description: "Get both damaging and goodfaith predictions for multiple revisions in parallel", params: [
      { key: "revisionIds", description: "Array of revision IDs" },
      { key: "wiki", description: "Wiki code (e.g., \"enwiki\"). If not provided, extracted from base URL" }
  ] },
]